@startuml

top to bottom direction
skinparam linetype ortho

class EmptyArrayException {
  + EmptyArrayException(String):
}
class UnreachableThresholdException {
  + UnreachableThresholdException(String):
}

@enduml
