@startuml

top to bottom direction

class ManagerRestController {
  + ManagerRestController(OaFManagerPort):
  + manageOrders(): ResponseEntity
  + manageConfirmations(): ResponseEntity
}

package impl{
    interface ManagerRestControllerIF << interface >> {
      + manageOrders(): ResponseEntity
      + manageConfirmations(): ResponseEntity
    }
}

ManagerRestController    -[#008200,dashed]-^  ManagerRestControllerIF
@enduml
