@startuml

left to right direction
skinparam linetype ortho

package exceptions{
    class EmptyFetchException {
      + EmptyFetchException(String):
    }
    class InconsistentDTOException {
      + InconsistentDTOException(String):
    }
}

package config{
    enum OafStatus << enumeration >> {
      - OafStatus(String):
      + SHIPPED: String
      + label: String
      + CONTENTERROR: String
      + CONFIRMED: String
      + OPENTRANSERROR: String
      + NEW: String
      + values(): OafStatus[]
      + toString(): String
      + valueOf(String): OafStatus
    }
    class OdooApiConfig {
      + OdooApiConfig():
      + PARTNER_ID_FIELD: String
      - online: boolean
      - uid: int
      + commmonConfig: XmlRpcClientConfigImpl
      + READ: String
      + db: String
      + models: XmlRpcClient
      + objectConfig: XmlRpcClientConfigImpl
      - log: Logger
      + RES_PARTNER: String
      + password: String
      + username: String
      + client: XmlRpcClient
      + FIELDS: String
      + EXECUTE_KW: String
      + url: String
      + getDb(): String
      + getPassword(): String
      + connect(): void
      + isOnline(): boolean
      + getUid(): int
      + getUrl(): String
    }
}

class OdooDataSender {
  + OdooDataSender(OdooApiConfig):
  - odoo: OdooApiConfig
  - log: Logger
  - ERROR_MSG_ODOODB: String
  - writeConfirmationMessage(String, ConfirmationStructure): String
  + signalShipped(Order): boolean
  - signal(Confirmation): boolean
  + signalOpenTransError(Order): boolean
  + signalConfirmation(Confirmation): boolean
  + signalContentError(Order): boolean
  - updateTo(String, String): boolean
  - createWorkflowAnnotation(String, ConfirmationStructure): void
  - signal(Order, OafStatus): boolean
}
class OdooOrderProvider {
  + OdooOrderProvider(OdooApiConfig):
  - ordine: Order
  - log: Logger
  - odoo: OdooApiConfig
  + fetchOrders(): boolean
  + popNewOrder(): Order
  + hasNewOrder(): boolean
  - fetchData(): boolean
}

package dto{}
package mapper{}

OafStatus                 +-[#820000,plain]-  OdooApiConfig
OdooDataSender           "1" *-[#595959,plain]-> "odoo\n1" OdooApiConfig
OdooOrderProvider        "1" *-[#595959,plain]-> "odoo\n1" OdooApiConfig
@enduml
