@startuml

left to right direction
skinparam linetype ortho

class BuyerID {
  + BuyerID(String, String):
  + BuyerID():
  - buyerId: String
  - type: String
  + setBuyerId(String): void
  + getType(): String
  + getBuyerId(): String
}
enum DeliveryDateType << enumeration >> {
  - DeliveryDateType(String):
  + FIXED:
  + OPTIONAL:
  - type: String
  + toString(): String
  + valueOf(String): DeliveryDateType
  + values(): DeliveryDateType[]
}
enum PartyType << enumeration >> {
  - PartyType(String):
  - type: String
  + SUPPLIER_SPECIFIC:
  + BUYER_SPECIFIC:
  + valueOf(String): PartyType
  + toString(): String
  + values(): PartyType[]
}
class XmlAddress {
  + XmlAddress(String, String, String, String, String, String):
  + XmlAddress():
  - city: String
  - zip: String
  - street: String
  - countryCoded: String
  - name: String
  - country: String
  - name3: String
  + getCity(): String
  + getCountry(): String
  + getName(): String
  + getZip(): String
  + getCountryCoded(): String
  + getStreet(): String
}
class XmlDeliveryDate {
  + XmlDeliveryDate(String, String, DeliveryDateType):
  + XmlDeliveryDate():
  - type: String
  - deliveryEndDate: String
  - deliveryStartDate: String
  + getDeliveryStartDate(): String
  + setDeliveryStartDate(String): void
  + getDeliveryEndDate(): String
  + setDeliveryEndDate(String): void
  + getType(): String
  + setType(String): void
}
class XmlOrderPartiesReference {
  + XmlOrderPartiesReference():
  + XmlOrderPartiesReference(String, PartyType, String, PartyType, String, PartyType):
  - supplierIdRef: XmlPartyID
  - buyerIdRef: XmlPartyID
  - shipmentPartiesRef: XmlShipmentPartiesReference
  + setSupplierIdRef(XmlPartyID): void
  + getSupplierIdRef(): XmlPartyID
  + setShipmentPartiesRef(XmlShipmentPartiesReference): void
  + setBuyerIdRef(XmlPartyID): void
  + getShipmentPartiesRef(): XmlShipmentPartiesReference
  + getBuyerIdRef(): XmlPartyID
}
class XmlParty {
  + XmlParty(XmlPartyID, String):
  + XmlParty():
  - partyRole: String
  - address: XmlAddress
  - partyId: XmlPartyID
  + setPartyId(XmlPartyID): void
  + setAddress(XmlAddress): void
  + setPartyRole(String): void
  + getAddress(): XmlAddress
  + getPartyRole(): String
  + getPartyId(): XmlPartyID
}
class XmlPartyID {
  + XmlPartyID(String):
  + XmlPartyID():
  + XmlPartyID(String, PartyType):
  - partyId: String
  - type: String
  + setPartyId(String): void
  + getPartyId(): String
  + setType(String): void
  + getType(): String
}
class XmlProductID {
  + XmlProductID(String, String, String):
  + XmlProductID():
  - supplierId: String
  - buyerId: BuyerID
  - descriptionShort: String
  + setBuyerId(BuyerID): void
  + getSupplierId(): String
  + setSupplierId(String): void
  + getDescriptionShort(): String
  + setDescriptionShort(String): void
  + getBuyerId(): BuyerID
}
class XmlShipmentPartiesReference {
  + XmlShipmentPartiesReference(XmlPartyID):
  + XmlShipmentPartiesReference():
  - deliveryIdRef: XmlPartyID
  + getDeliveryIdRef(): XmlPartyID
  + setDeliveryIdRef(XmlPartyID): void
}

XmlOrderPartiesReference    "1" *-[#595959,plain]-> "buyerIdRef\n1" XmlPartyID
XmlOrderPartiesReference     -[#595959,dashed]->  XmlPartyID                  : "«create»"
XmlOrderPartiesReference     -[#595959,dashed]->  XmlShipmentPartiesReference : "«create»"
XmlOrderPartiesReference    "1" *-[#595959,plain]-> "shipmentPartiesRef\n1" XmlShipmentPartiesReference
XmlParty                    "1" *-[#595959,plain]-> "address\n1" XmlAddress
XmlParty                    "1" *-[#595959,plain]-> "partyId\n1" XmlPartyID
XmlProductID                 -[#595959,dashed]->  BuyerID                     : "«create»"
XmlProductID                "1" *-[#595959,plain]-> "buyerId\n1" BuyerID
XmlShipmentPartiesReference "1" *-[#595959,plain]-> "deliveryIdRef\n1" XmlPartyID
@enduml
