@startuml

left to right direction
skinparam linetype ortho

class XmlAgreement {
  + XmlAgreement(String):
  - id: String
  + getId(): String
  + setId(String): void
}
class XmlItem {
  + XmlItem(OrderItem):
  - orderUnit: String
  - prodId: XmlProductID
  - quantity: float
  - lineItemId: int
  + getProdId(): XmlProductID
  + getOrderUnit(): String
  + getQuantity(): float
  + getLineItemId(): int
}
class XmlOrder {
  + XmlOrder(XmlOrderHeader, List<XmlItem>, XmlOrderSummary):
  - xsi: String
  - orderItem: List<XmlItem>
  + os: XmlOrderSummary
  - xmlns: String
  - version: String
  - bmecat: String
  + oh: XmlOrderHeader
  - schemaLocation: String
  - type: String
  + getType(): String
  + getXsi(): String
  + getXmlns(): String
  + getBmecat(): String
  + getSchemaLocation(): String
  + getOs(): XmlOrderSummary
  + getOh(): XmlOrderHeader
  + getVersion(): String
  + getOrderItem(): List<XmlItem>
}
class XmlOrderHeader {
  + XmlOrderHeader(OrderHeader):
  - orderInfo: XmlOrderInfo
  - agreement: XmlAgreement
  + getOrderInfo(): XmlOrderInfo
}
class XmlOrderInfo {
  + XmlOrderInfo(OrderHeader):
  - orderId: String
  - orderParties: List<XmlParty>
  - deliveryDate: XmlDeliveryDate
  - currency: String
  - orderDate: String
  - partialShipment: boolean
  - orderPartiesReference: XmlOrderPartiesReference
  + getOrderDate(): String
  + getOrderParties(): List<XmlParty>
  + getDeliveryDate(): XmlDeliveryDate
  + getOrderPartiesReference(): XmlOrderPartiesReference
  + getOrderId(): String
}
class XmlOrderSummary {
  + XmlOrderSummary(OrderSummary):
  - totalItemNum: int
  + getTotalItemNum(): int
}

XmlAgreement     +-[#820000,plain]-  XmlOrderHeader
XmlOrder        "1" *-[#595959,plain]-> "orderItem\n*" XmlItem
XmlOrder        "1" *-[#595959,plain]-> "oh\n1" XmlOrderHeader
XmlOrder        "1" *-[#595959,plain]-> "os\n1" XmlOrderSummary
XmlOrderHeader  "1" *-[#595959,plain]-> "agreement\n1" XmlAgreement
XmlOrderHeader   -[#595959,dashed]->  XmlAgreement    : "«create»"
XmlOrderHeader   -[#595959,dashed]->  XmlOrderInfo    : "«create»"
XmlOrderHeader  "1" *-[#595959,plain]-> "orderInfo\n1" XmlOrderInfo
@enduml
