@startuml

left to right direction
skinparam linetype ortho

class XmlAOCValue {
  + XmlAOCValue():
  - amount: float
  + setAmount(float): void
  + getAmount(): float
}
class XmlAllowOrCharge {
  + XmlAllowOrCharge():
  - descr: String
  - value: XmlAOCValue
  - type: String
  - name: String
  + gettype(): String
  + setType(String): void
  + getValue(): XmlAOCValue
  + getDescr(): String
  + getName(): String
  + setValue(XmlAOCValue): void
}
class XmlControlInfo {
  + XmlControlInfo():
  - generatorInfo: String
  - generationDate: String
  + getGeneratorInfo(): String
  + setGeneratorInfo(String): void
  + getGenerationDate(): String
  + setGenerationDate(String): void
}
class XmlOrderResponse {
  + XmlOrderResponse():
  - orderSummary: XmlOrderResponseSummary
  - xmlns: String
  - xsi: String
  - orderResponseItemList: List<XmlOrderResponseItem>
  - version: String
  - orderResponseHeader: XmlOrderResponseHeader
  - bmecat: String
  + setXsi(String): void
  + setVersion(String): void
  + setBmecat(String): void
  + getXmlns(): String
  + getXsi(): String
  + getVersion(): String
  + setXmlns(String): void
  + setOrderResponseHeader(XmlOrderResponseHeader): void
  + getOrderResponseItemList(): List<XmlOrderResponseItem>
  + setOrderSummary(XmlOrderResponseSummary): void
  + getBmecat(): String
  + getOrderSummary(): XmlOrderResponseSummary
  + getOrderResponseHeader(): XmlOrderResponseHeader
  + setOrderResponseItemList(List<XmlOrderResponseItem>): void
}
class XmlOrderResponseHeader {
  + XmlOrderResponseHeader():
  - controlInfo: XmlControlInfo
  - orderResponseInfo: XmlOrderResponseInfo
  + setControlInfo(XmlControlInfo): void
  + setOrderResponseInfo(XmlOrderResponseInfo): void
  + getControlInfo(): XmlControlInfo
  + getOrderResponseInfo(): XmlOrderResponseInfo
}
class XmlOrderResponseInfo {
  + XmlOrderResponseInfo():
  - altCustomerOrderId: String
  - parties: List<XmlParty>
  - orderResponseDate: String
  - supplierOrderId: String
  - remarks: XmlRemarks
  - currency: String
  - deliveryDate: XmlDeliveryDate
  - orderId: String
  - orderPartiesReference: XmlOrderPartiesReference
  - orderDate: String
  + setOrderResponseDate(String): void
  + setRemarks(XmlRemarks): void
  + getCurrency(): String
  + setAltCustomerOrderId(String): void
  + getParties(): List<XmlParty>
  + setOrderDate(String): void
  + getOrderResponseDate(): String
  + getSupplierOrderId(): String
  + getAltCustomerOrderId(): String
  + getDeliveryDate(): XmlDeliveryDate
  + setOrderPartiesReference(XmlOrderPartiesReference): void
  + setCurrency(String): void
  + getOrderDate(): String
  + setParties(List<XmlParty>): void
  + setDeliveryDate(XmlDeliveryDate): void
  + setOrderId(String): void
  + getRemarks(): XmlRemarks
  + getOrderPartiesReference(): XmlOrderPartiesReference
  + setSupplierOrderId(String): void
  + getOrderId(): String
}
class XmlOrderResponseItem {
  + XmlOrderResponseItem():
  - orderUnit: String
  - productFeatures: List<XmlProductFeature>
  - quantity: float
  - productId: XmlProductID
  - productPriceFix: XmlProductPriceFix
  - remarks: XmlRemarks
  - priceLineAmount: float
  - lineItemId: int
  - deliveryDate: XmlDeliveryDate
  + setOrderUnit(String): void
  + getProductPriceFix(): XmlProductPriceFix
  + getPriceLineAmount(): float
  + setProductPriceFix(XmlProductPriceFix): void
  + getProductId(): XmlProductID
  + getRemarks(): XmlRemarks
  + setRemarks(XmlRemarks): void
  + getQuantity(): float
  + setLineItemId(int): void
  + setProductId(XmlProductID): void
  + getProductFeatures(): List<XmlProductFeature>
  + setQuantity(float): void
  + getLineItemId(): int
  + setPriceLineAmount(float): void
  + setProductFeatures(List<XmlProductFeature>): void
  + getDeliveryDate(): XmlDeliveryDate
  + setDeliveryDate(XmlDeliveryDate): void
  + getOrderUnit(): String
}
class XmlOrderResponseSummary {
  + XmlOrderResponseSummary():
  - allowOrChargesFix: List<XmlAllowOrCharge>
  - totalItemNum: int
  - totalAmount: float
  + getTotalItemNum(): int
  + setTotalAmount(float): void
  + setAllowOrChargesFix(List<XmlAllowOrCharge>): void
  + setTotalItemNum(int): void
  + getTotalAmount(): float
  + getAllowOrChargesFix(): List<XmlAllowOrCharge>
}
class XmlPriceBaseFix {
  + XmlPriceBaseFix():
  - price: float
  - priceUnit: String
  + setPriceUnit(String): void
  + getPrice(): float
  + setPrice(float): void
  + getPriceUnit(): String
}
class XmlProductFeature {
  + XmlProductFeature():
  - fname: String
  - fvalue: float
  - funit: String
  + getFvalue(): float
  + setFvalue(float): void
  + getFunit(): String
  + setFunit(String): void
  + getFname(): String
  + setFname(String): void
}
class XmlProductPriceFix {
  + XmlProductPriceFix():
  - priceAmount: float
  - priceQuantity: int
  - taxDetailsFix: XmlTaxDetailsFix
  - priceBaseFix: XmlPriceBaseFix
  + getPriceQuantity(): int
  + getPriceBaseFix(): XmlPriceBaseFix
  + setPriceBaseFix(XmlPriceBaseFix): void
  + getPriceAmount(): float
  + setPriceQuantity(int): void
  + setTaxDetailsFix(XmlTaxDetailsFix): void
  + setPriceAmount(float): void
  + getTaxDetailsFix(): XmlTaxDetailsFix
}
class XmlRemarks {
  + XmlRemarks():
  - type: String
  - remarks: String
  + setType(String): void
  + getRemarks(): String
  + setRemarks(String): void
  + getType(): String
}
class XmlTaxDetailsFix {
  + XmlTaxDetailsFix():
  - tax: float
  - taxAmount: float
  + getTax(): float
  + getTaxAmount(): float
  + setTaxAmount(float): void
  + setTax(float): void
}

XmlAllowOrCharge        "1" *-[#595959,plain]-> "value\n1" XmlAOCValue
XmlOrderResponse        "1" *-[#595959,plain]-> "orderResponseHeader\n1" XmlOrderResponseHeader
XmlOrderResponse        "1" *-[#595959,plain]-> "orderResponseItemList\n*" XmlOrderResponseItem
XmlOrderResponse        "1" *-[#595959,plain]-> "orderSummary\n1" XmlOrderResponseSummary
XmlOrderResponseHeader  "1" *-[#595959,plain]-> "controlInfo\n1" XmlControlInfo
XmlOrderResponseHeader  "1" *-[#595959,plain]-> "orderResponseInfo\n1" XmlOrderResponseInfo
XmlOrderResponseInfo    "1" *-[#595959,plain]-> "remarks\n1" XmlRemarks
XmlOrderResponseItem    "1" *-[#595959,plain]-> "productFeatures\n*" XmlProductFeature
XmlOrderResponseItem    "1" *-[#595959,plain]-> "productPriceFix\n1" XmlProductPriceFix
XmlOrderResponseItem    "1" *-[#595959,plain]-> "remarks\n1" XmlRemarks
XmlOrderResponseSummary "1" *-[#595959,plain]-> "allowOrChargesFix\n*" XmlAllowOrCharge
XmlProductPriceFix      "1" *-[#595959,plain]-> "priceBaseFix\n1" XmlPriceBaseFix
XmlProductPriceFix      "1" *-[#595959,plain]-> "taxDetailsFix\n1" XmlTaxDetailsFix
@enduml
