@startuml
top to bottom direction
skinparam linetype ortho

class Order {
  + Order(OrderStructure, String):
  - deliveryDateContent: boolean
  - articleNumber: boolean
  - orderID: String
  - quantityMeasure: boolean
  - data: OrderStructure
  - deliveryDate: boolean
  - customerNumber: boolean
  - quantity: QuantityFieldValue
  - deliveryLocationNumber: boolean
  + setDeliveryLocationNumber(boolean): void
  + setArticleNumber(boolean): void
  + hasOpenTransError(): boolean
  + getOrderID(): String
  + getData(): OrderStructure
  + isQuantityMeasure(): boolean
  + setCustomerNumber(boolean): void
  + setDeliveryDateContent(boolean): void
  + hasContentError(): boolean
  + setQuantityMeasure(boolean): void
  + isDeliveryDate(): boolean
  + isArticleNumber(): boolean
  + setQuantity(QuantityFieldValue): void
  + getQuantity(): QuantityFieldValue
  + setDeliveryDate(boolean): void
  + isCustomerNumber(): boolean
  + isDeliveryLocationNumber(): boolean
  + isDeliveryDateContent(): boolean
}
class OrderHeader {
  + OrderHeader():
  + OrderHeader(OrderHeader):
  - orderDate: String
  - supplierID: String
  - currency: String
  - deliveryID: String
  - buyerID: String
  - endDate: String
  - orderID: String
  - deliveryIDRef: String
  - supplierIDRef: String
  - startDate: String
  - buyerIDRef: String
  + getOrderDate(): String
  + setEndDate(String): void
  + getSupplierID(): String
  + setBuyerIDRef(String): void
  + getDeliveryIDRef(): String
  + setCurrency(String): void
  + setDeliveryIDRef(String): void
  + getSupplierIDRef(): String
  + setSupplierID(String): void
  + getBuyerIDRef(): String
  + getEndDate(): String
  + getBuyerID(): String
  + getOrderID(): String
  + setDeliveryID(String): void
  + setOrderDate(String): void
  + getCurrency(): String
  + setSupplierIDRef(String): void
  + setOrderID(String): void
  + setBuyerID(String): void
  + getDeliveryID(): String
  + toString(): String
  + setStartDate(String): void
  + getStartDate(): String
}
class OrderItem {
  + OrderItem():
  - supplierID: String
  - descriptionShort: String
  - lineItemID: String
  - quantity: String
  - buyerID: String
  - orderUnit: String
  + setOrderUnit(String): void
  + setLineItemID(String): void
  + getBuyerID(): String
  + getQuantity(): String
  + setDescriptionShort(String): void
  + setQuantity(String): void
  + getDescriptionShort(): String
  + setSupplierID(String): void
  + getLineItemID(): String
  + setBuyerID(String): void
  + getOrderUnit(): String
  + getSupplierID(): String
  + toString(): String
}
class OrderStructure {
  + OrderStructure():
  + OrderStructure(OrderStructure):
  - header: OrderHeader
  - itemList: OrderItem[]
  - orderSummary: OrderSummary
  + getOrderSummary(): OrderSummary
  + setOrderSummary(OrderSummary): void
  + setHeader(OrderHeader): void
  + toString(): String
  + getItemList(): OrderItem[]
  + getHeader(): OrderHeader
  + setItemList(OrderItem[]): void
}
class OrderSummary {
  + OrderSummary():
  + OrderSummary(OrderSummary):
  - totalItemNum: int
  + setTotalItemNum(int): void
  + getTotalItemNum(): int
  + toString(): String
}
enum QuantityFieldValue << enumeration >> {
  + QuantityFieldValue():
  + INTEGER:
  + FLOAT_WITH_COMMA:
  + NAN:
  + FLOAT_WITH_DOT:
  + valueOf(String): QuantityFieldValue
  + values(): QuantityFieldValue[]
}

Order              "1" *-[#595959,plain]-> "data\n1" OrderStructure
Order               -[#595959,dashed]->  OrderStructure     : "«create»"
Order              "1" *-[#595959,plain]-> "quantity\n1" QuantityFieldValue
OrderStructure      -[#595959,dashed]->  OrderHeader        : "«create»"
OrderStructure     "1" *-[#595959,plain]-> "header\n1" OrderHeader
OrderStructure     "1" *-[#595959,plain]-> "itemList\n*" OrderItem
OrderStructure      -[#595959,dashed]->  OrderSummary       : "«create»"
OrderStructure     "1" *-[#595959,plain]-> "orderSummary\n1" OrderSummary
@enduml
