@startuml
left to right direction


' Package diagram per com.beemediate.beemediate (completo, classi solo intestazione)

package controller.http{
    interface ManagerRestControllerIF
    package impl {
    class ManagerRestController <<RestController>>
    }
}

package domain {
  package pojo {
    package order {
      class Order
      class OrderStructure
      class OrderHeader
      class OrderItem
      class OrderSummary
      enum QuantityFieldValue
    }
    package confirmation {
      class Confirmation
      class ConfirmationStructure
    }
  }

  package ports {
    package infrastructure {
      package odoo {
        interface OrderProviderPort
        interface DataSenderPort
      }
      package ftp {
        interface FTPHandlerPort
        interface ConfirmationProviderPort
        interface OrderSenderPort
        interface ConfirmationHandlerPort
      }

      package filesystem {
        interface SupplierCatalogReaderPort
      }
    }
    package controller {
      interface OaFManagerPort
    }
  }

  package service {
    class OaFBatchManager
    class OaFBuffer
    package validator{
        interface OaFValidatorIF
        package impl{
            class OaFValidator
        }
    }
  }

  package utils {
    class StringHandler
    class BoundedBuffer
  }
}

package infrastructure {
  package odoo {
    class OdooOrderProvider <<Component>>
    class OdooDataSender <<Component>>


    package config {
        class OdooApiConfig
    }

    package exceptions {
      class EmptyFetchException
      class InconsistentDTOException
    }

    package mapper {
      class OrderMapper
      class AttributeMapper
    }

    package dto {
        class ArticoloPreventivoDTO
        class CompagniaDTO
        class ConsegnaDTO
        class ContattoConsegnaDTO
        class DestinazioneDTO
        class FornitoreDTO
        class IdentifierDTO
        class PreventivoDTO
        class ProdottoDTO
        class ProdottoFornitoreDTO
    }
  }

  package ftp {
    class FTPReader <<Component>>
    class FTPWriter <<Component>>

    package config {
      class FTPConfig
    }

    package dto {

      package confirmation {
          class XmlOrderResponseInfo
          class XmlOrderResponseItem
          class XmlOrderResponseSummary
          class XmlPriceBaseFix
          class XmlProductFeature
          class XmlProductPriceFix
          class XmlRemarks
          class XmlTaxDetailsFix
          class XmlAOCValue
      }

      package commons {
        class BuyerID
        enum PartyType
        enum DelivertDateType
        class XmlAddress
        class XmlDeliveryDate
        class XmlOrderPartiesReference
        class XmlParty
        class XmlPartyID
        class XmlProductID
        class XmlShipmentPartiesReference
      }
      package order {
        class XmlItem
        class XmlOrder
        class XmlOrderHeader
        class XmlOrderInfo
        class XMlOrderSummary
      }
    }

    package exceptions {
      class WrongPathException
    }

    package mapper {
      class DataMapper
    }
  }

  package filesystem {
    class XlsxAdapter <<Component>>
  }
}

' Relazioni (implementazioni / dipendenze)
ManagerRestController ..|> ManagerRestControllerIF : implements

OaFValidator ..|> domain.service.validator.OaFValidatorIF : implements
OaFBatchManager ..|> domain.ports.controller.OaFManagerPort : implements

OdooOrderProvider ..|> domain.ports.infrastructure.odoo.OrderProviderPort : implements
OdooDataSender ..|> domain.ports.infrastructure.odoo.DataSenderPort : implements
FTPWriter -[#41B343,dashed]-|> domain.ports.infrastructure.ftp.FTPHandlerPort : implements
FTPReader -[#41B343,dashed]-|> domain.ports.infrastructure.ftp.ConfirmationProviderPort : implements
FTPHandlerPort ..|> ConfirmationHandlerPort  : implements
FTPHandlerPort ..|> OrderSenderPort  : implements
XlsxAdapter ..|> domain.ports.infrastructure.filesystem.SupplierCatalogReaderPort : implements


@enduml